# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.github_repo }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: CDSS Common Documentation
tagline: Helpful Docs for Course Staff
description: Helpful docs for course staff
author: Silas Santini
# You should use either light or dark as the theme.
color_scheme: light

baseurl: '/docs' # the subpath of your site
url: 'https://berkeley-cdss.github.io' # the hostname & protocol for your site, e.g. http://example.com

# Custom variables, which can appear in various places around the website
email: seamless-learning@berkeley.edu
course_department: dsus # required for config validator to work

# Set these auxiliary links as you wish - they show up on the top right
aux_links:
  Berkeley CDSS GitHub:
    - 'https://github.com/berkeley-cdss'
  Edit this site on GitHub:
    - 'https://github.com/berkeley-cdss/docs'

berkeley_theme_options:
  show_logo_in_sidebar: true

# Collections for website data
collections:
  contributors:
    sort_by: name

# The sitemap **must** be enabled. It's published as /baseurl/sitemap.xml
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-include-cache
  - jekyll-jupyter-notebook

# Default layouts for each collection type
defaults:
  - scope:
      path: '_contributors'
      type: contributors
    values:
      layout: contributor
      height: 300
      subpath: '/assets/images/'
      width: 300


######################################################################
# Just the Docs / Berkeley Class Site Common Config
# Options below here will likely not need to be configured..
######################################################################
callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

sass:
  style: expanded
  sass_dir: _sass
  sourcemap: always
  quiet_deps: true
  verbose: false

# Theme settings
theme: just-the-docs
search_enabled: true
heading_anchors: true
permalink: pretty

## Footer Content.
# You should probably not change these, but may add to footer_content if necessary.
# Replace `true` with any additional HTML that you would like to add.
# Footer *must* included the accessibility text defined in footer_custom.html
footer_content: true
back_to_top: true
back_to_top_text: "Back to Top"
last_edit_timestamp: true
last_edit_time_format: '%m %d, %Y at %H:%M'

# Compilation settings used by compress-html plugin:
# https://github.com/penibelst/jekyll-compress-html/tree/v3.2.0?tab=readme-ov-file
compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false

# Native Jeykll build options
# You likely shouldn't need to touch these, but they are documented here just in case.
# https://jekyllrb.com/docs/configuration/options/

# This makes it easier when pushing to a static directory.
# The default false removes files in that directory, which is useful for when you unpublish pages.
# keep_files: false

# Likely not necessary, but a google default for Berkeley
timezone: America/Los_Angeles

# Note: dotfiles are excluded by default. .htaccess is included as a common case.
include:
  - LICENSE
  - .htaccess
  - robots.txt

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/
  - README.md
  - CONTRIBUTING.md
  - tmp/
  - script/
  - spec/
  - node_modules/
